version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "Deps"
    groups:
      python-packages:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "actions/*"
    ignore:
      - dependency-name: "greenbone/actions"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "Deps"
