# SPDX-FileCopyrightText: 2020-2023 Greenbone AG
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

from pathlib import Path

import tomlkit

from ...helper import override
from .._errors import VersionError
from .._version import Version, VersionUpdate
from ..schemes import PEP440VersioningScheme
from ._python import PythonVersionCommand

TEMPLATE = """# pylint: disable=invalid-name

# THIS IS AN AUTOGENERATED FILE. DO NOT TOUCH!

__version__ = "{}"\n"""


# This class is used for Python projects using UV
class UvVersionCommand(PythonVersionCommand):
    uv_lock_file_name = "uv.lock"
    _uv_lock_file_path: Path | None = None

    @property
    def uv_lock_file_path(self) -> Path:
        if self._uv_lock_file_path:
            return self._uv_lock_file_path

        self._uv_lock_file_path = self.project_file_path.parent / "uv.lock"
        return self._uv_lock_file_path

    @override
    def get_version_from_pyproject_toml(self) -> Version:
        """
        Return the version information from the [project] section of the
        pyproject.toml file.
        """

        if (
            "project" in self.pyproject_toml
            and "version" in self.pyproject_toml["project"]  # type: ignore[operator]
        ):
            return PEP440VersioningScheme.parse_version(
                str(self.pyproject_toml["project"]["version"])  # type: ignore[operator, index]
            )

        raise VersionError(
            f"Version information not found in {self.project_file_path} file."
        )

    @override
    def update_pyproject_version(
        self,
        new_version: Version,
    ) -> None:
        """
        Update the version in the pyproject.toml file
        """
        pyproject_toml = tomlkit.parse(
            self.project_file_path.read_text(encoding="utf-8")
        )

        # create [project] section if it does not exist and set the version
        if "project" not in pyproject_toml:
            project_table = tomlkit.table()
            pyproject_toml["project"] = project_table

        # ensure the version is available in the [project] section
        pyproject_toml["project"]["version"] = str(new_version)

        self.project_file_path.write_text(
            tomlkit.dumps(pyproject_toml), encoding="utf-8"
        )

    def _update_uv_lock_file(self, new_version: Version) -> None:
        """
        Update the uv.lock file with the new version
        """
        if not self.uv_lock_file_path.exists():
            raise VersionError(
                f"uv.lock file not found at {self.uv_lock_file_path}. "
                "Cannot update version."
            )

        uv_lock_content = tomlkit.parse(
            self.uv_lock_file_path.read_text(encoding="utf-8")
        )

        if "package" not in uv_lock_content:
            raise VersionError(
                f"[[package]] entries not found in {self.uv_lock_file_path}. "
                "Cannot update version."
            )

        project_name = self.pyproject_toml.get("project", {}).get("name")
        if project_name is None:
            raise VersionError(
                f"Project name not found in {self.project_file_path}. "
                "Cannot update version."
            )

        for package in uv_lock_content["package"]:
            if package.get("name") == project_name:
                package["version"] = str(new_version)
                break
        else:
            raise VersionError(
                f"Package {project_name!r} not found in {self.uv_lock_file_path}. "
                "Cannot update version."
            )

        self.uv_lock_file_path.write_text(
            tomlkit.dumps(uv_lock_content), encoding="utf-8"
        )

    @override
    def update_version(
        self, new_version: Version, *, force: bool = False
    ) -> VersionUpdate:
        new_pep440_version = PEP440VersioningScheme.from_version(new_version)

        try:
            try:
                current_version = self.get_current_version()
            except VersionError:
                # maybe no version module exists yet. fallback to version from
                # pyproject.toml
                current_version = self.get_version_from_pyproject_toml()

            current_converted_version = self.versioning_scheme.from_version(
                current_version
            )

            if not force and new_pep440_version == current_version:
                return VersionUpdate(
                    previous=current_converted_version, new=new_version
                )
        except VersionError:
            # just ignore current version and override it
            current_converted_version = None

        try:
            self.update_pyproject_version(new_version=new_pep440_version)
        except OSError as e:
            raise VersionError(
                "Unable to update version in "
                f"{self.project_file_path.absolute()}. Error was {e}"
            ) from e

        try:
            self._update_uv_lock_file(new_version=new_pep440_version)
        except OSError as e:
            raise VersionError(
                "Unable to update uv.lock file in "
                f"{self.uv_lock_file_path.absolute()}. Error was {e}"
            ) from e

        try:
            self.update_version_file(new_version=new_pep440_version)
        except OSError as e:
            raise VersionError(
                "Unable to update version in "
                f"{self.version_file_path.absolute()}. Error was {e}"
            ) from e

        return VersionUpdate(
            previous=current_converted_version,
            new=new_version,
            changed_files=[
                self.version_file_path,
                self.uv_lock_file_path,
                self.project_file_path,
            ],
        )

    @override
    def project_found(self) -> bool:
        """
        Returns True if a command has detected a corresponding project
        """
        return (
            self.project_file_path.exists() and self.uv_lock_file_path.exists()
        )
